use books;
INSERT INTO categories (id_categories, categories) VALUES (1, 'Fiction');
INSERT INTO categories (id_categories, categories) VALUES (2, 'Religion');
INSERT INTO categories (id_categories, categories) VALUES (3, 'Biography & Autobiography');
INSERT INTO categories (id_categories, categories) VALUES (4, 'Technology & Engineering');
INSERT INTO categories (id_categories, categories) VALUES (5, 'Law');
INSERT INTO categories (id_categories, categories) VALUES (6, 'Health & Fitness');
INSERT INTO categories (id_categories, categories) VALUES (7, 'History');
INSERT INTO categories (id_categories, categories) VALUES (8, 'Foreign Language Study');
INSERT INTO categories (id_categories, categories) VALUES (9, 'Medical');
INSERT INTO categories (id_categories, categories) VALUES (10, 'Art');
INSERT INTO categories (id_categories, categories) VALUES (11, 'Local author');
INSERT INTO categories (id_categories, categories) VALUES (12, 'Gardening');
INSERT INTO categories (id_categories, categories) VALUES (13, 'Sports & Recreation');
INSERT INTO categories (id_categories, categories) VALUES (14, 'Juvenile Nonfiction');
INSERT INTO categories (id_categories, categories) VALUES (15, 'Business & Economics');
INSERT INTO categories (id_categories, categories) VALUES (16, 'Family & Relationships');
INSERT INTO categories (id_categories, categories) VALUES (17, 'Comics & Graphic Novels');
INSERT INTO categories (id_categories, categories) VALUES (18, 'Body, Mind & Spirit');
INSERT INTO categories (id_categories, categories) VALUES (19, 'ABAP/4 (Computer program language)');
INSERT INTO categories (id_categories, categories) VALUES (20, 'Psychology');
INSERT INTO categories (id_categories, categories) VALUES (21, 'Nature');
INSERT INTO categories (id_categories, categories) VALUES (22, 'Social Science');
INSERT INTO categories (id_categories, categories) VALUES (23, 'Political Science');
INSERT INTO categories (id_categories, categories) VALUES (24, 'Language Arts & Disciplines');
INSERT INTO categories (id_categories, categories) VALUES (25, 'Music');
INSERT INTO categories (id_categories, categories) VALUES (26, 'Juvenile Fiction');
INSERT INTO categories (id_categories, categories) VALUES (27, 'Education');
INSERT INTO categories (id_categories, categories) VALUES (28, 'Bibles');
INSERT INTO categories (id_categories, categories) VALUES (29, 'Self-Help');
INSERT INTO categories (id_categories, categories) VALUES (30, 'Reference');
INSERT INTO categories (id_categories, categories) VALUES (31, 'Poetry');
INSERT INTO categories (id_categories, categories) VALUES (32, 'Science');
INSERT INTO categories (id_categories, categories) VALUES (33, 'Goddesses');
INSERT INTO categories (id_categories, categories) VALUES (34, 'Mathematics');
INSERT INTO categories (id_categories, categories) VALUES (35, 'Literary Collections');
INSERT INTO categories (id_categories, categories) VALUES (36, 'Humor');
INSERT INTO categories (id_categories, categories) VALUES (37, 'Computers');
INSERT INTO categories (id_categories, categories) VALUES (38, 'Architecture');
INSERT INTO categories (id_categories, categories) VALUES (39, 'Performing Arts');
INSERT INTO categories (id_categories, categories) VALUES (40, 'Literary Criticism');
INSERT INTO categories (id_categories, categories) VALUES (41, 'Travel');
INSERT INTO categories (id_categories, categories) VALUES (42, 'Crafts & Hobbies');
INSERT INTO categories (id_categories, categories) VALUES (43, 'Philosophy');
INSERT INTO categories (id_categories, categories) VALUES (44, 'English language');
INSERT INTO categories (id_categories, categories) VALUES (45, 'Photography');
INSERT INTO categories (id_categories, categories) VALUES (46, 'Cooking');
INSERT INTO categories (id_categories, categories) VALUES (47, 'Games & Activities');
INSERT INTO categories (id_categories, categories) VALUES (48, 'True Crime');
INSERT INTO categories (id_categories, categories) VALUES (49, 'Games');
INSERT INTO categories (id_categories, categories) VALUES (50, 'Drama');
INSERT INTO categories (id_categories, categories) VALUES (51, 'Self-publishing');
INSERT INTO categories (id_categories, categories) VALUES (52, 'Transportation');
INSERT INTO categories (id_categories, categories) VALUES (53, 'Study Aids');
INSERT INTO categories (id_categories, categories) VALUES (54, 'Young Adult Fiction');
INSERT INTO categories (id_categories, categories) VALUES (55, 'House & Home');
INSERT INTO categories (id_categories, categories) VALUES (56, 'Pets');
INSERT INTO categories (id_categories, categories) VALUES (57, 'Canadian fiction');
INSERT INTO categories (id_categories, categories) VALUES (58, 'Prostate');
INSERT INTO categories (id_categories, categories) VALUES (59, 'Bible');
INSERT INTO categories (id_categories, categories) VALUES (60, 'Antiques & Collectibles');
INSERT INTO categories (id_categories, categories) VALUES (61, 'Prophecies');
INSERT INTO categories (id_categories, categories) VALUES (62, 'Detroit (Mich.)');
INSERT INTO categories (id_categories, categories) VALUES (63, 'Decoration and ornament');
INSERT INTO categories (id_categories, categories) VALUES (64, 'Accelerated readers');
INSERT INTO categories (id_categories, categories) VALUES (65, 'Young Adult Nonfiction');
INSERT INTO categories (id_categories, categories) VALUES (66, 'Theater');
INSERT INTO categories (id_categories, categories) VALUES (67, 'Construction industry');
INSERT INTO categories (id_categories, categories) VALUES (68, 'Diplomatic and consular service');
INSERT INTO categories (id_categories, categories) VALUES (69, 'Application software');
INSERT INTO categories (id_categories, categories) VALUES (70, 'Production management');
INSERT INTO categories (id_categories, categories) VALUES (71, 'Boxcar children (Fictitous characters)');
INSERT INTO categories (id_categories, categories) VALUES (72, 'Computer storage devices');
INSERT INTO categories (id_categories, categories) VALUES (73, 'United States');
INSERT INTO categories (id_categories, categories) VALUES (74, 'Copyright');
INSERT INTO categories (id_categories, categories) VALUES (75, 'Authors, New Zealand');
INSERT INTO categories (id_categories, categories) VALUES (76, 'Immigrants');
INSERT INTO categories (id_categories, categories) VALUES (77, 'International relations');
INSERT INTO categories (id_categories, categories) VALUES (78, 'Psychoanalysis and literature');
INSERT INTO categories (id_categories, categories) VALUES (79, 'NATURE');
INSERT INTO categories (id_categories, categories) VALUES (80, 'English fiction');
INSERT INTO categories (id_categories, categories) VALUES (81, 'Political science');
INSERT INTO categories (id_categories, categories) VALUES (82, 'Hebrew literature, Modern');
INSERT INTO categories (id_categories, categories) VALUES (83, 'Christmas stories');
INSERT INTO categories (id_categories, categories) VALUES (84, 'Autistic children');
INSERT INTO categories (id_categories, categories) VALUES (85, 'Barbados');
INSERT INTO categories (id_categories, categories) VALUES (86, 'Social sciences');
INSERT INTO categories (id_categories, categories) VALUES (87, 'Criminal procedure');
INSERT INTO categories (id_categories, categories) VALUES (88, 'Lords prayer');
INSERT INTO categories (id_categories, categories) VALUES (89, 'Insurance');
INSERT INTO categories (id_categories, categories) VALUES (90, 'Detective and mystery stories, English');
INSERT INTO categories (id_categories, categories) VALUES (91, 'Admirals');
INSERT INTO categories (id_categories, categories) VALUES (92, 'Theology, Doctrinal');
INSERT INTO categories (id_categories, categories) VALUES (93, 'Families');
INSERT INTO categories (id_categories, categories) VALUES (94, 'Salvation');
INSERT INTO categories (id_categories, categories) VALUES (95, 'Mass');
INSERT INTO categories (id_categories, categories) VALUES (96, 'Japan');
INSERT INTO categories (id_categories, categories) VALUES (97, 'Family-owned business enterprises');
INSERT INTO categories (id_categories, categories) VALUES (98, 'Comic books, strips, etc');
INSERT INTO categories (id_categories, categories) VALUES (99, 'FAMILY & RELATIONSHIPS');
INSERT INTO categories (id_categories, categories) VALUES (100, 'Conduct of life');
INSERT INTO categories (id_categories, categories) VALUES (101, 'Apostles');
INSERT INTO categories (id_categories, categories) VALUES (102, 'Change');
INSERT INTO categories (id_categories, categories) VALUES (103, 'Impressionism');
INSERT INTO categories (id_categories, categories) VALUES (104, 'Brass instrument players');
INSERT INTO categories (id_categories, categories) VALUES (105, 'Design');
INSERT INTO categories (id_categories, categories) VALUES (106, 'Afghanistan');
INSERT INTO categories (id_categories, categories) VALUES (107, 'Caribbean literature');
INSERT INTO categories (id_categories, categories) VALUES (108, 'Cooking, Irish');
INSERT INTO categories (id_categories, categories) VALUES (109, 'Prostitution');
INSERT INTO categories (id_categories, categories) VALUES (110, 'Paris');
INSERT INTO categories (id_categories, categories) VALUES (111, 'HEALTH & FITNESS');
INSERT INTO categories (id_categories, categories) VALUES (112, 'Flamenco');
INSERT INTO categories (id_categories, categories) VALUES (113, 'ART');
INSERT INTO categories (id_categories, categories) VALUES (114, 'Detective and mystery stories');
INSERT INTO categories (id_categories, categories) VALUES (115, 'Authors, American');
INSERT INTO categories (id_categories, categories) VALUES (116, 'Chemotaxonomy');
INSERT INTO categories (id_categories, categories) VALUES (117, 'Motion picture actors and actresses');
INSERT INTO categories (id_categories, categories) VALUES (118, 'Interpersonal relations');
INSERT INTO categories (id_categories, categories) VALUES (119, 'Science fiction');
INSERT INTO categories (id_categories, categories) VALUES (120, 'Dakota Territory');
INSERT INTO categories (id_categories, categories) VALUES (121, 'Europe, Eastern');
INSERT INTO categories (id_categories, categories) VALUES (122, 'Entropy');
INSERT INTO categories (id_categories, categories) VALUES (123, 'Cleanliness');
INSERT INTO categories (id_categories, categories) VALUES (124, 'Paranormal romance stories');
INSERT INTO categories (id_categories, categories) VALUES (125, 'Rock music');
INSERT INTO categories (id_categories, categories) VALUES (126, 'Mexican Americans');
INSERT INTO categories (id_categories, categories) VALUES (127, 'Antisemitism');
INSERT INTO categories (id_categories, categories) VALUES (128, 'Ghost stories');
INSERT INTO categories (id_categories, categories) VALUES (129, 'Abused women');
INSERT INTO categories (id_categories, categories) VALUES (130, 'Computer networks');
INSERT INTO categories (id_categories, categories) VALUES (131, 'Bullies');
INSERT INTO categories (id_categories, categories) VALUES (132, 'Indians of North America');
INSERT INTO categories (id_categories, categories) VALUES (133, 'Presidents');
INSERT INTO categories (id_categories, categories) VALUES (134, 'Detective and mystery stories, American');
INSERT INTO categories (id_categories, categories) VALUES (135, 'Freemasonry');
INSERT INTO categories (id_categories, categories) VALUES (136, 'Cooperativeness');
INSERT INTO categories (id_categories, categories) VALUES (137, 'Shenandoah National Park (Va.)');
INSERT INTO categories (id_categories, categories) VALUES (138, 'Hand');
INSERT INTO categories (id_categories, categories) VALUES (139, 'Covenant theology');
INSERT INTO categories (id_categories, categories) VALUES (140, 'Mystery.');
INSERT INTO categories (id_categories, categories) VALUES (141, 'Holistic medicine');
INSERT INTO categories (id_categories, categories) VALUES (142, 'Colombia');
INSERT INTO categories (id_categories, categories) VALUES (143, 'Adoptees');
INSERT INTO categories (id_categories, categories) VALUES (144, 'Canada');
INSERT INTO categories (id_categories, categories) VALUES (145, 'Commons');
INSERT INTO categories (id_categories, categories) VALUES (146, 'Christian life');
INSERT INTO categories (id_categories, categories) VALUES (147, 'Apologetics');
INSERT INTO categories (id_categories, categories) VALUES (148, 'Childrens stories');
INSERT INTO categories (id_categories, categories) VALUES (149, 'Limited partnership');
INSERT INTO categories (id_categories, categories) VALUES (150, 'Civilization, Modern');
INSERT INTO categories (id_categories, categories) VALUES (151, 'Anglo-Saxons');
INSERT INTO categories (id_categories, categories) VALUES (152, 'Finger sucking');
INSERT INTO categories (id_categories, categories) VALUES (153, 'Radio');
INSERT INTO categories (id_categories, categories) VALUES (154, 'Meditation');
INSERT INTO categories (id_categories, categories) VALUES (155, 'Communication in marriage');
INSERT INTO categories (id_categories, categories) VALUES (156, 'Orphans');
INSERT INTO categories (id_categories, categories) VALUES (157, 'Athletes with disabilities');
INSERT INTO categories (id_categories, categories) VALUES (158, 'Cookery');
INSERT INTO categories (id_categories, categories) VALUES (159, 'Attitude (Psychology)');
INSERT INTO categories (id_categories, categories) VALUES (160, 'Historical geography');
INSERT INTO categories (id_categories, categories) VALUES (161, 'BIOGRAPHY & AUTOBIOGRAPHY');
INSERT INTO categories (id_categories, categories) VALUES (162, 'Babies');
INSERT INTO categories (id_categories, categories) VALUES (163, 'Communism');
INSERT INTO categories (id_categories, categories) VALUES (164, 'Abused children');
INSERT INTO categories (id_categories, categories) VALUES (165, 'Christian women');
INSERT INTO categories (id_categories, categories) VALUES (166, 'LANGUAGE ARTS & DISCIPLINES');
INSERT INTO categories (id_categories, categories) VALUES (167, 'Academic achievement');
INSERT INTO categories (id_categories, categories) VALUES (168, 'Biodiversity conservation');
INSERT INTO categories (id_categories, categories) VALUES (169, 'Good and evil');
INSERT INTO categories (id_categories, categories) VALUES (170, 'Business cycles');
INSERT INTO categories (id_categories, categories) VALUES (171, 'Aquarium fishes');
INSERT INTO categories (id_categories, categories) VALUES (172, 'Nutrition');
INSERT INTO categories (id_categories, categories) VALUES (173, 'Herbs');
INSERT INTO categories (id_categories, categories) VALUES (174, 'Science fiction, American');
INSERT INTO categories (id_categories, categories) VALUES (175, 'Eskimos');
INSERT INTO categories (id_categories, categories) VALUES (176, 'FICTION');
INSERT INTO categories (id_categories, categories) VALUES (177, 'Actresses');
INSERT INTO categories (id_categories, categories) VALUES (178, 'Baghdad (Iraq)');
INSERT INTO categories (id_categories, categories) VALUES (179, 'Guitar music, Arranged');
INSERT INTO categories (id_categories, categories) VALUES (180, 'Blacks');
INSERT INTO categories (id_categories, categories) VALUES (181, 'Childrens poetry');
INSERT INTO categories (id_categories, categories) VALUES (182, 'Electronic books');
INSERT INTO categories (id_categories, categories) VALUES (183, 'Women');
INSERT INTO categories (id_categories, categories) VALUES (184, 'Viticulture');
INSERT INTO categories (id_categories, categories) VALUES (185, 'Clouds');
INSERT INTO categories (id_categories, categories) VALUES (186, 'Artists, Dutch');
INSERT INTO categories (id_categories, categories) VALUES (187, 'Mormon Church');
INSERT INTO categories (id_categories, categories) VALUES (188, 'Prosthodontics');
INSERT INTO categories (id_categories, categories) VALUES (189, 'Bioethics');
INSERT INTO categories (id_categories, categories) VALUES (190, 'Monasticism and religious orders');
INSERT INTO categories (id_categories, categories) VALUES (191, 'Communication of technical information');
INSERT INTO categories (id_categories, categories) VALUES (192, 'Animals');
INSERT INTO categories (id_categories, categories) VALUES (193, 'Indian art');
INSERT INTO categories (id_categories, categories) VALUES (194, 'AIDS (Disease)');
INSERT INTO categories (id_categories, categories) VALUES (195, 'Space colonies');
INSERT INTO categories (id_categories, categories) VALUES (196, 'Sales promotion');
INSERT INTO categories (id_categories, categories) VALUES (197, 'Alcoholics');
INSERT INTO categories (id_categories, categories) VALUES (198, 'Bombardment');
INSERT INTO categories (id_categories, categories) VALUES (199, 'Back Bay (Boston, Mass.)');
INSERT INTO categories (id_categories, categories) VALUES (200, 'Self-help techniques');
INSERT INTO categories (id_categories, categories) VALUES (201, 'Authors, English');
INSERT INTO categories (id_categories, categories) VALUES (202, 'Defense (Criminal procedure)');
INSERT INTO categories (id_categories, categories) VALUES (203, 'Man-woman relationships');
INSERT INTO categories (id_categories, categories) VALUES (204, 'Grace (Theology)');
INSERT INTO categories (id_categories, categories) VALUES (205, 'Imperialism');
INSERT INTO categories (id_categories, categories) VALUES (206, 'Charity-schools');
INSERT INTO categories (id_categories, categories) VALUES (207, 'English literature');
INSERT INTO categories (id_categories, categories) VALUES (208, 'Drama in education');
INSERT INTO categories (id_categories, categories) VALUES (209, 'Latin American literature');
INSERT INTO categories (id_categories, categories) VALUES (210, 'Communication interpersonnelle');
INSERT INTO categories (id_categories, categories) VALUES (211, 'Canvas embroidery');
INSERT INTO categories (id_categories, categories) VALUES (212, 'Dystopias');
INSERT INTO categories (id_categories, categories) VALUES (213, 'Miniature books');
INSERT INTO categories (id_categories, categories) VALUES (214, 'Arab-Israeli conflict');
INSERT INTO categories (id_categories, categories) VALUES (215, 'Printing');
INSERT INTO categories (id_categories, categories) VALUES (216, 'Artificial intelligence');
INSERT INTO categories (id_categories, categories) VALUES (217, 'Cayman Brac Island (Cayman Islands)');
INSERT INTO categories (id_categories, categories) VALUES (218, 'Simonov carbine');
INSERT INTO categories (id_categories, categories) VALUES (219, 'Political fiction');
INSERT INTO categories (id_categories, categories) VALUES (220, 'French language');
INSERT INTO categories (id_categories, categories) VALUES (221, 'Love');
INSERT INTO categories (id_categories, categories) VALUES (222, 'Knowledge, Theory of');
INSERT INTO categories (id_categories, categories) VALUES (223, 'Founding');
INSERT INTO categories (id_categories, categories) VALUES (224, 'Rock musicians');
INSERT INTO categories (id_categories, categories) VALUES (225, 'Tai chi');
INSERT INTO categories (id_categories, categories) VALUES (226, 'Deconstruction');
INSERT INTO categories (id_categories, categories) VALUES (227, 'World War, 1939-1945');
INSERT INTO categories (id_categories, categories) VALUES (228, 'Childrens stories, English');
INSERT INTO categories (id_categories, categories) VALUES (229, 'Faith');
INSERT INTO categories (id_categories, categories) VALUES (230, 'Indian mythology');
INSERT INTO categories (id_categories, categories) VALUES (231, 'Child rearing');
INSERT INTO categories (id_categories, categories) VALUES (232, 'Federal aid to nonprofit organizations');
INSERT INTO categories (id_categories, categories) VALUES (233, 'Charlie (Fictitious character : Child)');
INSERT INTO categories (id_categories, categories) VALUES (234, 'Finance, Personal');
INSERT INTO categories (id_categories, categories) VALUES (235, 'First Coalition, War of the, 1792-1797');
INSERT INTO categories (id_categories, categories) VALUES (236, 'Electronic book');
INSERT INTO categories (id_categories, categories) VALUES (237, 'Autobiographies');
INSERT INTO categories (id_categories, categories) VALUES (238, 'Martial arts');
INSERT INTO categories (id_categories, categories) VALUES (239, 'Contra Costa County (Calif.)');
INSERT INTO categories (id_categories, categories) VALUES (240, 'Volvo 740 automobile');
INSERT INTO categories (id_categories, categories) VALUES (241, 'Planets');
INSERT INTO categories (id_categories, categories) VALUES (242, 'Treasure troves.');
INSERT INTO categories (id_categories, categories) VALUES (243, 'Brothers and sisters');
INSERT INTO categories (id_categories, categories) VALUES (244, 'Fourth of July orations');
INSERT INTO categories (id_categories, categories) VALUES (245, 'Critical thinking');
INSERT INTO categories (id_categories, categories) VALUES (246, 'Hindi language');
INSERT INTO categories (id_categories, categories) VALUES (247, 'Dutch language');
INSERT INTO categories (id_categories, categories) VALUES (248, 'Animal behavior');
INSERT INTO categories (id_categories, categories) VALUES (249, 'Telecommunication');
INSERT INTO categories (id_categories, categories) VALUES (250, 'Thunderstorms');
INSERT INTO categories (id_categories, categories) VALUES (251, 'Marxian school of sociology');
INSERT INTO categories (id_categories, categories) VALUES (252, 'Latin language');
INSERT INTO categories (id_categories, categories) VALUES (253, 'Puzzles');
INSERT INTO categories (id_categories, categories) VALUES (254, 'Internal medicine');
INSERT INTO categories (id_categories, categories) VALUES (255, 'Bridegrooms');
INSERT INTO categories (id_categories, categories) VALUES (256, 'Agape');
INSERT INTO categories (id_categories, categories) VALUES (257, 'Cancer');
INSERT INTO categories (id_categories, categories) VALUES (258, 'African American journalists');
INSERT INTO categories (id_categories, categories) VALUES (259, 'American wit and humor');
INSERT INTO categories (id_categories, categories) VALUES (260, 'Aging');
INSERT INTO categories (id_categories, categories) VALUES (261, 'Mediums');
INSERT INTO categories (id_categories, categories) VALUES (262, 'American fiction');
INSERT INTO categories (id_categories, categories) VALUES (263, 'Italy');
INSERT INTO categories (id_categories, categories) VALUES (264, 'Foot');
INSERT INTO categories (id_categories, categories) VALUES (265, 'Marine biology');
INSERT INTO categories (id_categories, categories) VALUES (266, 'Dystopian plays');
INSERT INTO categories (id_categories, categories) VALUES (267, 'Decoration and ornament, Architectural');
INSERT INTO categories (id_categories, categories) VALUES (268, 'Great Britain');
INSERT INTO categories (id_categories, categories) VALUES (269, 'Cooking (Spices)');
INSERT INTO categories (id_categories, categories) VALUES (270, 'Violin');
INSERT INTO categories (id_categories, categories) VALUES (271, 'Adobe Premiere');
INSERT INTO categories (id_categories, categories) VALUES (272, 'Career changes');
INSERT INTO categories (id_categories, categories) VALUES (273, 'Erotic literature');
INSERT INTO categories (id_categories, categories) VALUES (274, 'Business forecasting');
INSERT INTO categories (id_categories, categories) VALUES (275, 'Doctor Who (Fictitious character)');
INSERT INTO categories (id_categories, categories) VALUES (276, 'Hebrides (Scotland)');
INSERT INTO categories (id_categories, categories) VALUES (277, 'Brand name products');
INSERT INTO categories (id_categories, categories) VALUES (278, 'Ocean bottom');
INSERT INTO categories (id_categories, categories) VALUES (279, 'Adventure stories');
INSERT INTO categories (id_categories, categories) VALUES (280, 'Congenital heart disease');
INSERT INTO categories (id_categories, categories) VALUES (281, 'Crystals');
INSERT INTO categories (id_categories, categories) VALUES (282, 'Asia');
INSERT INTO categories (id_categories, categories) VALUES (283, 'Clock and watch makers');
INSERT INTO categories (id_categories, categories) VALUES (284, 'African Americans');
INSERT INTO categories (id_categories, categories) VALUES (285, 'China');
INSERT INTO categories (id_categories, categories) VALUES (286, 'Human anatomy');
INSERT INTO categories (id_categories, categories) VALUES (287, 'Christian literature, Early');
INSERT INTO categories (id_categories, categories) VALUES (288, 'Creative thinking');
INSERT INTO categories (id_categories, categories) VALUES (289, 'Industrial management');
INSERT INTO categories (id_categories, categories) VALUES (290, 'Mysticism');
INSERT INTO categories (id_categories, categories) VALUES (291, 'Active server pages');
INSERT INTO categories (id_categories, categories) VALUES (292, 'Cruise ships');
INSERT INTO categories (id_categories, categories) VALUES (293, 'Laundry');
INSERT INTO categories (id_categories, categories) VALUES (294, 'Second law of thermodynamics');
INSERT INTO categories (id_categories, categories) VALUES (295, 'Capitalism');
INSERT INTO categories (id_categories, categories) VALUES (296, 'Authors, Puerto Rican');
INSERT INTO categories (id_categories, categories) VALUES (297, 'Esperanto');
INSERT INTO categories (id_categories, categories) VALUES (298, 'Computer network architectures');
INSERT INTO categories (id_categories, categories) VALUES (299, 'Academic writing');
INSERT INTO categories (id_categories, categories) VALUES (300, 'Creation');
INSERT INTO categories (id_categories, categories) VALUES (301, 'Embezzlement');
INSERT INTO categories (id_categories, categories) VALUES (302, 'Arab American women');
INSERT INTO categories (id_categories, categories) VALUES (303, 'Lorenz cipher system');
INSERT INTO categories (id_categories, categories) VALUES (304, 'Intuition');
INSERT INTO categories (id_categories, categories) VALUES (305, 'Catholic schools');
INSERT INTO categories (id_categories, categories) VALUES (306, 'Guerrilla warfare');
INSERT INTO categories (id_categories, categories) VALUES (307, 'Messerschmitt 163 (Fighter plane)');
INSERT INTO categories (id_categories, categories) VALUES (308, 'Arab nationalism');
INSERT INTO categories (id_categories, categories) VALUES (309, 'Beauty, Personal');
INSERT INTO categories (id_categories, categories) VALUES (310, 'Electric currents, Alternating');
INSERT INTO categories (id_categories, categories) VALUES (311, 'Spanish language');
INSERT INTO categories (id_categories, categories) VALUES (312, 'Airplanes, Military');
INSERT INTO categories (id_categories, categories) VALUES (313, 'City and town life');
INSERT INTO categories (id_categories, categories) VALUES (314, 'Germany');
INSERT INTO categories (id_categories, categories) VALUES (315, 'Emotions');
INSERT INTO categories (id_categories, categories) VALUES (316, 'Healing');
INSERT INTO categories (id_categories, categories) VALUES (317, 'Famines');
INSERT INTO categories (id_categories, categories) VALUES (318, 'Legislators');
INSERT INTO categories (id_categories, categories) VALUES (319, 'Fathers and daughters');
INSERT INTO categories (id_categories, categories) VALUES (320, 'Singing');
INSERT INTO categories (id_categories, categories) VALUES (321, 'Kitsch');
INSERT INTO categories (id_categories, categories) VALUES (322, 'Critical realism');
INSERT INTO categories (id_categories, categories) VALUES (323, 'Automobile driver education');
INSERT INTO categories (id_categories, categories) VALUES (324, 'Computers and civilization');
INSERT INTO categories (id_categories, categories) VALUES (325, 'LAW');
INSERT INTO categories (id_categories, categories) VALUES (326, 'Assessment');
INSERT INTO categories (id_categories, categories) VALUES (327, 'Ethnomusicology');
INSERT INTO categories (id_categories, categories) VALUES (328, 'Bullying');
INSERT INTO categories (id_categories, categories) VALUES (329, 'Imaginary wars and battles');
INSERT INTO categories (id_categories, categories) VALUES (330, 'Politicians');
INSERT INTO categories (id_categories, categories) VALUES (331, 'India');
INSERT INTO categories (id_categories, categories) VALUES (332, 'Yao (Southeast Asian people)');
INSERT INTO categories (id_categories, categories) VALUES (333, 'Botany');
INSERT INTO categories (id_categories, categories) VALUES (334, 'Historic sites');
INSERT INTO categories (id_categories, categories) VALUES (335, 'Creative ability in business.');
INSERT INTO categories (id_categories, categories) VALUES (336, 'Computer network protocols');
INSERT INTO categories (id_categories, categories) VALUES (337, 'Church group work with youth');
INSERT INTO categories (id_categories, categories) VALUES (338, 'Femininity');
INSERT INTO categories (id_categories, categories) VALUES (339, 'Contracts');
INSERT INTO categories (id_categories, categories) VALUES (340, 'Bashfulness');
INSERT INTO categories (id_categories, categories) VALUES (341, 'Christian education of preschool children');
INSERT INTO categories (id_categories, categories) VALUES (342, 'Radar');
INSERT INTO categories (id_categories, categories) VALUES (343, '3D studio');
INSERT INTO categories (id_categories, categories) VALUES (344, 'Archival resources');
INSERT INTO categories (id_categories, categories) VALUES (345, 'Dollar, American');
INSERT INTO categories (id_categories, categories) VALUES (346, 'Organizational change');
INSERT INTO categories (id_categories, categories) VALUES (347, 'Jews');
INSERT INTO categories (id_categories, categories) VALUES (348, 'Card games');
INSERT INTO categories (id_categories, categories) VALUES (349, 'Animal treatment');
INSERT INTO categories (id_categories, categories) VALUES (350, 'Clothing and dress');
INSERT INTO categories (id_categories, categories) VALUES (351, 'Small claims courts');
INSERT INTO categories (id_categories, categories) VALUES (352, 'Classical drama');
INSERT INTO categories (id_categories, categories) VALUES (353, 'Domestic fiction');
INSERT INTO categories (id_categories, categories) VALUES (354, 'RELIGION');
INSERT INTO categories (id_categories, categories) VALUES (355, 'Communication in humanities');
INSERT INTO categories (id_categories, categories) VALUES (356, 'Clairvoyants');
INSERT INTO categories (id_categories, categories) VALUES (357, 'Ethnologie');
INSERT INTO categories (id_categories, categories) VALUES (358, 'Executions and executioners');
INSERT INTO categories (id_categories, categories) VALUES (359, 'Iraq War, 2003-');
INSERT INTO categories (id_categories, categories) VALUES (360, 'Occupations');
INSERT INTO categories (id_categories, categories) VALUES (361, 'Chakras');
INSERT INTO categories (id_categories, categories) VALUES (362, 'Catholic preaching');
INSERT INTO categories (id_categories, categories) VALUES (363, 'Christian education of children');
INSERT INTO categories (id_categories, categories) VALUES (364, 'Interior architecture');
INSERT INTO categories (id_categories, categories) VALUES (365, 'Mexican American women');
INSERT INTO categories (id_categories, categories) VALUES (366, 'Bengali fiction');
INSERT INTO categories (id_categories, categories) VALUES (367, 'Hawaii');
INSERT INTO categories (id_categories, categories) VALUES (368, 'Historical fiction');
INSERT INTO categories (id_categories, categories) VALUES (369, 'Deafblind women');
INSERT INTO categories (id_categories, categories) VALUES (370, 'Year 2000 date conversion (Computer systems)');
INSERT INTO categories (id_categories, categories) VALUES (371, 'Art, Japanese');
INSERT INTO categories (id_categories, categories) VALUES (372, 'Chicago (Ill.)');
INSERT INTO categories (id_categories, categories) VALUES (373, 'Boston Tea Party, Boston, Mass., 1773');
INSERT INTO categories (id_categories, categories) VALUES (374, 'Childrens literature');
INSERT INTO categories (id_categories, categories) VALUES (375, 'Christianity and politics');
INSERT INTO categories (id_categories, categories) VALUES (376, 'Mexico');
INSERT INTO categories (id_categories, categories) VALUES (377, 'Bodybuilding');
INSERT INTO categories (id_categories, categories) VALUES (378, 'Interior decoration');
INSERT INTO categories (id_categories, categories) VALUES (379, 'Primitivity (Psychoanalysis)');
INSERT INTO categories (id_categories, categories) VALUES (380, 'Estate planning');
INSERT INTO categories (id_categories, categories) VALUES (381, 'Tierra del Fuego (Argentina and Chile)');
INSERT INTO categories (id_categories, categories) VALUES (382, 'Space vehicles');
INSERT INTO categories (id_categories, categories) VALUES (383, 'Hell in literature');
INSERT INTO categories (id_categories, categories) VALUES (384, 'Death');
INSERT INTO categories (id_categories, categories) VALUES (385, 'Exercise');
INSERT INTO categories (id_categories, categories) VALUES (386, 'Finance');
INSERT INTO categories (id_categories, categories) VALUES (387, 'American wit and humor, Pictorial');
INSERT INTO categories (id_categories, categories) VALUES (388, 'Artists');
INSERT INTO categories (id_categories, categories) VALUES (389, 'Discipline of children');
INSERT INTO categories (id_categories, categories) VALUES (390, 'Greenwich (Conn.)');
INSERT INTO categories (id_categories, categories) VALUES (391, 'Atlantic Coast (U.S.)');
INSERT INTO categories (id_categories, categories) VALUES (392, 'Fourth dimension');
INSERT INTO categories (id_categories, categories) VALUES (393, 'Abnormalities, Human');
INSERT INTO categories (id_categories, categories) VALUES (394, 'Bereavement');
INSERT INTO categories (id_categories, categories) VALUES (395, 'Economists');
INSERT INTO categories (id_categories, categories) VALUES (396, 'Christians');
INSERT INTO categories (id_categories, categories) VALUES (397, 'Baptists');
INSERT INTO categories (id_categories, categories) VALUES (398, 'Monastic and religious life');
INSERT INTO categories (id_categories, categories) VALUES (399, 'Authors, Guinean');
INSERT INTO categories (id_categories, categories) VALUES (400, 'Dream interpretation');
INSERT INTO categories (id_categories, categories) VALUES (401, 'Authors, Austrian');
INSERT INTO categories (id_categories, categories) VALUES (402, 'Technology');
INSERT INTO categories (id_categories, categories) VALUES (403, 'Displacement (Psychology)');
INSERT INTO categories (id_categories, categories) VALUES (404, 'Women authors, American');
INSERT INTO categories (id_categories, categories) VALUES (405, 'Electronic data processing');
INSERT INTO categories (id_categories, categories) VALUES (406, 'Will');
INSERT INTO categories (id_categories, categories) VALUES (407, 'Jewish literature');
INSERT INTO categories (id_categories, categories) VALUES (408, 'Conversation');
INSERT INTO categories (id_categories, categories) VALUES (409, 'Drawings');
INSERT INTO categories (id_categories, categories) VALUES (410, 'Inheritance and succession');
INSERT INTO categories (id_categories, categories) VALUES (411, 'Alaska');
INSERT INTO categories (id_categories, categories) VALUES (412, 'St. Albans (England)');
INSERT INTO categories (id_categories, categories) VALUES (413, 'Church and the world');
INSERT INTO categories (id_categories, categories) VALUES (414, 'Adjoining landowners');
INSERT INTO categories (id_categories, categories) VALUES (415, 'Fairy tales');
INSERT INTO categories (id_categories, categories) VALUES (416, 'Learning');
INSERT INTO categories (id_categories, categories) VALUES (417, 'Argentine fiction');
INSERT INTO categories (id_categories, categories) VALUES (418, 'Fraud');
INSERT INTO categories (id_categories, categories) VALUES (419, 'Tabla');
INSERT INTO categories (id_categories, categories) VALUES (420, 'Ocean liners');
INSERT INTO categories (id_categories, categories) VALUES (421, 'COOKING');
INSERT INTO categories (id_categories, categories) VALUES (422, 'Alternative medicine');
INSERT INTO categories (id_categories, categories) VALUES (423, 'Biography');
INSERT INTO categories (id_categories, categories) VALUES (424, 'Delusions');
INSERT INTO categories (id_categories, categories) VALUES (425, 'Cookery, Indonesian');
INSERT INTO categories (id_categories, categories) VALUES (426, 'Corporate governance');
INSERT INTO categories (id_categories, categories) VALUES (427, 'England');
INSERT INTO categories (id_categories, categories) VALUES (428, 'September 11 Terrorist Attacks, 2001');
INSERT INTO categories (id_categories, categories) VALUES (429, 'Church history');
INSERT INTO categories (id_categories, categories) VALUES (430, 'Africa, Sub-Saharan');
INSERT INTO categories (id_categories, categories) VALUES (431, 'Matopo Hills (Zimbabwe)');
INSERT INTO categories (id_categories, categories) VALUES (432, 'Mauser rifle');
INSERT INTO categories (id_categories, categories) VALUES (433, 'Atlantic Coast (France)');
INSERT INTO categories (id_categories, categories) VALUES (434, 'Firearms');
INSERT INTO categories (id_categories, categories) VALUES (435, 'Springfield rifle');
INSERT INTO categories (id_categories, categories) VALUES (436, 'Crimes without victims');
INSERT INTO categories (id_categories, categories) VALUES (437, 'Mental healing');
INSERT INTO categories (id_categories, categories) VALUES (438, 'Philosophers');
INSERT INTO categories (id_categories, categories) VALUES (439, 'Cinematography');
INSERT INTO categories (id_categories, categories) VALUES (440, 'College student orientation');
INSERT INTO categories (id_categories, categories) VALUES (441, 'Imaginary letters');
INSERT INTO categories (id_categories, categories) VALUES (442, 'Charitable uses, trusts, and foundations');
INSERT INTO categories (id_categories, categories) VALUES (443, 'Harvest festivals');
INSERT INTO categories (id_categories, categories) VALUES (444, 'Codependency');
INSERT INTO categories (id_categories, categories) VALUES (445, 'Celts');
INSERT INTO categories (id_categories, categories) VALUES (446, 'Molecular structure');
INSERT INTO categories (id_categories, categories) VALUES (447, 'Country life');
INSERT INTO categories (id_categories, categories) VALUES (448, 'Chronic pain');
INSERT INTO categories (id_categories, categories) VALUES (449, 'Meaning (Philosophy)');
INSERT INTO categories (id_categories, categories) VALUES (450, 'Photograph albums');
INSERT INTO categories (id_categories, categories) VALUES (451, 'Photojournalism');
INSERT INTO categories (id_categories, categories) VALUES (452, 'Marshals');
INSERT INTO categories (id_categories, categories) VALUES (453, 'English drama');
INSERT INTO categories (id_categories, categories) VALUES (454, 'Autism spectrum disorders');
INSERT INTO categories (id_categories, categories) VALUES (455, 'Administración de riesgos');
INSERT INTO categories (id_categories, categories) VALUES (456, 'Motion picture audiences');
INSERT INTO categories (id_categories, categories) VALUES (457, 'Poliomyelitis');
INSERT INTO categories (id_categories, categories) VALUES (458, 'Belief and doubt');
INSERT INTO categories (id_categories, categories) VALUES (459, 'Estados Unidos - Política militar');
INSERT INTO categories (id_categories, categories) VALUES (460, 'Ghosts');
INSERT INTO categories (id_categories, categories) VALUES (461, 'Office practice');
INSERT INTO categories (id_categories, categories) VALUES (462, 'Mahāmudrā (Tantric rite)');
INSERT INTO categories (id_categories, categories) VALUES (463, 'Bodhicitta (Buddhism)');
INSERT INTO categories (id_categories, categories) VALUES (464, 'Bilingual');
INSERT INTO categories (id_categories, categories) VALUES (465, 'English poetry');
INSERT INTO categories (id_categories, categories) VALUES (466, 'Associations, institutions, etc');
INSERT INTO categories (id_categories, categories) VALUES (467, 'Rose culture');
INSERT INTO categories (id_categories, categories) VALUES (468, 'Lesson planning');
INSERT INTO categories (id_categories, categories) VALUES (469, 'Aunts');
INSERT INTO categories (id_categories, categories) VALUES (470, 'Current Events');
INSERT INTO categories (id_categories, categories) VALUES (471, 'MEDICAL');
INSERT INTO categories (id_categories, categories) VALUES (472, 'Girls');
INSERT INTO categories (id_categories, categories) VALUES (473, 'Business ethics in motion pictures');
INSERT INTO categories (id_categories, categories) VALUES (474, 'Burma');
INSERT INTO categories (id_categories, categories) VALUES (475, 'Collective memory');
INSERT INTO categories (id_categories, categories) VALUES (476, 'Asia, Central');
INSERT INTO categories (id_categories, categories) VALUES (477, 'Automobile mechanics');
INSERT INTO categories (id_categories, categories) VALUES (478, 'Behavior');
INSERT INTO categories (id_categories, categories) VALUES (479, 'Flute players');
INSERT INTO categories (id_categories, categories) VALUES (480, 'Mothers');
INSERT INTO categories (id_categories, categories) VALUES (481, 'Composition (Music)');
INSERT INTO categories (id_categories, categories) VALUES (482, 'American periodicals');
INSERT INTO categories (id_categories, categories) VALUES (483, 'Golf');
INSERT INTO categories (id_categories, categories) VALUES (484, 'Creole dialects, English');
INSERT INTO categories (id_categories, categories) VALUES (485, 'Carving (Decorative arts)');
INSERT INTO categories (id_categories, categories) VALUES (486, 'Social psychology');
INSERT INTO categories (id_categories, categories) VALUES (487, 'Birth certificates');
INSERT INTO categories (id_categories, categories) VALUES (488, 'Authors, Japanese');
INSERT INTO categories (id_categories, categories) VALUES (489, 'Computer animation');
INSERT INTO categories (id_categories, categories) VALUES (490, 'Physicists');
INSERT INTO categories (id_categories, categories) VALUES (491, 'World War, 1914-1918');
INSERT INTO categories (id_categories, categories) VALUES (492, 'Rifles');
INSERT INTO categories (id_categories, categories) VALUES (493, 'Ballads, English');
INSERT INTO categories (id_categories, categories) VALUES (494, 'Diodes');
INSERT INTO categories (id_categories, categories) VALUES (495, 'Electronic circuit design');
INSERT INTO categories (id_categories, categories) VALUES (496, 'Eskimo languages');
INSERT INTO categories (id_categories, categories) VALUES (497, 'Acculturation');
INSERT INTO categories (id_categories, categories) VALUES (498, 'Social problems');
INSERT INTO categories (id_categories, categories) VALUES (499, 'War stories');
INSERT INTO categories (id_categories, categories) VALUES (500, 'Children');
INSERT INTO categories (id_categories, categories) VALUES (501, 'Character');
INSERT INTO categories (id_categories, categories) VALUES (502, 'Inhalant abuse');
INSERT INTO categories (id_categories, categories) VALUES (503, 'Marketing research');
INSERT INTO categories (id_categories, categories) VALUES (504, 'Autism');
INSERT INTO categories (id_categories, categories) VALUES (505, 'Missouri River Valley');
INSERT INTO categories (id_categories, categories) VALUES (506, 'Immortality');
INSERT INTO categories (id_categories, categories) VALUES (507, 'Buddhism');
INSERT INTO categories (id_categories, categories) VALUES (508, 'Language arts (Middle school)');
INSERT INTO categories (id_categories, categories) VALUES (509, 'Architects');
INSERT INTO categories (id_categories, categories) VALUES (510, 'Embedded computer systems');
INSERT INTO categories (id_categories, categories) VALUES (511, 'Animal experimentation');
INSERT INTO categories (id_categories, categories) VALUES (512, 'Marriage');
INSERT INTO categories (id_categories, categories) VALUES (513, 'Avocado');
INSERT INTO categories (id_categories, categories) VALUES (514, 'Cats');
INSERT INTO categories (id_categories, categories) VALUES (515, 'JUVENILE NONFICTION');
INSERT INTO categories (id_categories, categories) VALUES (516, 'Bioenergetic psychotherapy');
INSERT INTO categories (id_categories, categories) VALUES (517, 'Adultery');
INSERT INTO categories (id_categories, categories) VALUES (518, 'Spiritual life');
INSERT INTO categories (id_categories, categories) VALUES (519, 'Erotic poetry, Canadian');
INSERT INTO categories (id_categories, categories) VALUES (520, 'Discoveries in geography');
INSERT INTO categories (id_categories, categories) VALUES (521, 'Environmental psychology');
INSERT INTO categories (id_categories, categories) VALUES (522, 'Savannah (Ga.)');
INSERT INTO categories (id_categories, categories) VALUES (523, 'Inyo National Forest (Calif. and Nev.)');
INSERT INTO categories (id_categories, categories) VALUES (524, 'Hindu mathematics');
INSERT INTO categories (id_categories, categories) VALUES (525, 'Sufism');
INSERT INTO categories (id_categories, categories) VALUES (526, 'AutoCAD (Computer file)');
INSERT INTO categories (id_categories, categories) VALUES (527, 'Catholics');
INSERT INTO categories (id_categories, categories) VALUES (528, 'Music trade');
INSERT INTO categories (id_categories, categories) VALUES (529, 'Veterinarian and Client');
INSERT INTO categories (id_categories, categories) VALUES (530, 'Hospitals');
INSERT INTO categories (id_categories, categories) VALUES (531, 'Housing');
INSERT INTO categories (id_categories, categories) VALUES (532, 'College readers');
INSERT INTO categories (id_categories, categories) VALUES (533, 'Sanskrit language');
INSERT INTO categories (id_categories, categories) VALUES (534, 'Academic libraries');
INSERT INTO categories (id_categories, categories) VALUES (535, 'Colors');
INSERT INTO categories (id_categories, categories) VALUES (536, 'Algebra');
INSERT INTO categories (id_categories, categories) VALUES (537, 'Business enterprises');
INSERT INTO categories (id_categories, categories) VALUES (538, 'Anthroposophy');
INSERT INTO categories (id_categories, categories) VALUES (539, 'Hippies');
INSERT INTO categories (id_categories, categories) VALUES (540, 'Jamaica');
INSERT INTO categories (id_categories, categories) VALUES (541, 'Coast changes');
INSERT INTO categories (id_categories, categories) VALUES (542, 'Gifted persons');
INSERT INTO categories (id_categories, categories) VALUES (543, 'C++ (Computer program language)');
INSERT INTO categories (id_categories, categories) VALUES (544, 'Awareness');
INSERT INTO categories (id_categories, categories) VALUES (545, 'Nonprofit organizations');
INSERT INTO categories (id_categories, categories) VALUES (546, 'France');
INSERT INTO categories (id_categories, categories) VALUES (547, 'Books and reading');
INSERT INTO categories (id_categories, categories) VALUES (548, 'Architecture, Modern');
INSERT INTO categories (id_categories, categories) VALUES (549, 'Information technology');
INSERT INTO categories (id_categories, categories) VALUES (550, 'Commercial statistics');
INSERT INTO categories (id_categories, categories) VALUES (551, 'Gluttony');
INSERT INTO categories (id_categories, categories) VALUES (552, 'Shadow (Psychoanalysis)');
INSERT INTO categories (id_categories, categories) VALUES (553, 'Genealogy');
INSERT INTO categories (id_categories, categories) VALUES (554, 'Command of troops');
INSERT INTO categories (id_categories, categories) VALUES (555, 'Criminal investigation');
INSERT INTO categories (id_categories, categories) VALUES (556, 'Concentration camps');
INSERT INTO categories (id_categories, categories) VALUES (557, 'Tibet (China)');
INSERT INTO categories (id_categories, categories) VALUES (558, 'Celebrities');
INSERT INTO categories (id_categories, categories) VALUES (559, 'Civilization, Medieval');
INSERT INTO categories (id_categories, categories) VALUES (560, 'Climatic changes');
INSERT INTO categories (id_categories, categories) VALUES (561, 'Interfaith marriage');
INSERT INTO categories (id_categories, categories) VALUES (562, 'Signs and symbols');
INSERT INTO categories (id_categories, categories) VALUES (563, 'Horror tales, American');
INSERT INTO categories (id_categories, categories) VALUES (564, 'Creative writing');
INSERT INTO categories (id_categories, categories) VALUES (565, 'Cookery, African');
INSERT INTO categories (id_categories, categories) VALUES (566, 'Justice');
INSERT INTO categories (id_categories, categories) VALUES (567, 'Church year meditations');
INSERT INTO categories (id_categories, categories) VALUES (568, 'Country homes');
INSERT INTO categories (id_categories, categories) VALUES (569, 'Australian poetry');
INSERT INTO categories (id_categories, categories) VALUES (570, 'I AM Religious Activity');
INSERT INTO categories (id_categories, categories) VALUES (571, 'California, Northern');
INSERT INTO categories (id_categories, categories) VALUES (572, 'Maori (New Zealand people)');
INSERT INTO categories (id_categories, categories) VALUES (573, 'Hasidism');
INSERT INTO categories (id_categories, categories) VALUES (574, 'Bkaʼ-gdams-pa (Sect)');
INSERT INTO categories (id_categories, categories) VALUES (575, 'Bombings');
INSERT INTO categories (id_categories, categories) VALUES (576, 'Predator huntings');
INSERT INTO categories (id_categories, categories) VALUES (577, 'Editors');
INSERT INTO categories (id_categories, categories) VALUES (578, 'GAMES');
INSERT INTO categories (id_categories, categories) VALUES (579, 'Australia');
INSERT INTO categories (id_categories, categories) VALUES (580, 'Art and literature');
INSERT INTO categories (id_categories, categories) VALUES (581, 'Electronystagmography');
INSERT INTO categories (id_categories, categories) VALUES (582, 'Lebanon');
INSERT INTO categories (id_categories, categories) VALUES (583, 'Medicine, Tibetan');
INSERT INTO categories (id_categories, categories) VALUES (584, 'Flea markets');
INSERT INTO categories (id_categories, categories) VALUES (585, 'Bond, James (Fictitious character)');
INSERT INTO categories (id_categories, categories) VALUES (586, 'Aran Islands (Ireland)');
INSERT INTO categories (id_categories, categories) VALUES (587, 'Dalziel, Andrew (Fictitious character)');
INSERT INTO categories (id_categories, categories) VALUES (588, 'Commandments (Judaism)');
INSERT INTO categories (id_categories, categories) VALUES (589, 'Middle East');
INSERT INTO categories (id_categories, categories) VALUES (590, 'Korean War, 1950-1953');
INSERT INTO categories (id_categories, categories) VALUES (591, 'Chinese poetry');
INSERT INTO categories (id_categories, categories) VALUES (592, 'Conservatism');
INSERT INTO categories (id_categories, categories) VALUES (593, 'Czechoslovakia');
INSERT INTO categories (id_categories, categories) VALUES (594, 'Journalism');
INSERT INTO categories (id_categories, categories) VALUES (595, 'Businessmen');
INSERT INTO categories (id_categories, categories) VALUES (596, 'Obsessive-compulsive disorder');
INSERT INTO categories (id_categories, categories) VALUES (597, 'Inner cities');
INSERT INTO categories (id_categories, categories) VALUES (598, 'Sex role');
INSERT INTO categories (id_categories, categories) VALUES (599, 'Sports administration');
INSERT INTO categories (id_categories, categories) VALUES (600, 'Ceramic sculpture');
INSERT INTO categories (id_categories, categories) VALUES (601, 'American drama');
INSERT INTO categories (id_categories, categories) VALUES (602, 'Contracting out');
INSERT INTO categories (id_categories, categories) VALUES (603, 'Golf courses');
INSERT INTO categories (id_categories, categories) VALUES (604, 'Korean language');
INSERT INTO categories (id_categories, categories) VALUES (605, 'Tibet Autonomous Region (China)');
INSERT INTO categories (id_categories, categories) VALUES (606, 'Minnesota literature');
INSERT INTO categories (id_categories, categories) VALUES (607, 'Arts');
INSERT INTO categories (id_categories, categories) VALUES (608, 'Christian fiction');
INSERT INTO categories (id_categories, categories) VALUES (609, 'Differential equations');
INSERT INTO categories (id_categories, categories) VALUES (610, 'Deadlands (Game)');
INSERT INTO categories (id_categories, categories) VALUES (611, 'Astrology');
INSERT INTO categories (id_categories, categories) VALUES (612, 'Environmental toxicology');
INSERT INTO categories (id_categories, categories) VALUES (613, 'Muscles');
INSERT INTO categories (id_categories, categories) VALUES (614, 'Feminist theology');
INSERT INTO categories (id_categories, categories) VALUES (615, 'Immune system');
INSERT INTO categories (id_categories, categories) VALUES (616, 'Environmental economics');
INSERT INTO categories (id_categories, categories) VALUES (617, 'Wit and humor');
INSERT INTO categories (id_categories, categories) VALUES (618, 'Ark of the Covenant');
INSERT INTO categories (id_categories, categories) VALUES (619, 'Atmosphere');
INSERT INTO categories (id_categories, categories) VALUES (620, 'Assisi (Italy)');
INSERT INTO categories (id_categories, categories) VALUES (621, 'Arctic regions');
INSERT INTO categories (id_categories, categories) VALUES (622, 'City planning');
INSERT INTO categories (id_categories, categories) VALUES (623, 'Amusements');
INSERT INTO categories (id_categories, categories) VALUES (624, 'Readers');
INSERT INTO categories (id_categories, categories) VALUES (625, 'Electrodynamics');
INSERT INTO categories (id_categories, categories) VALUES (626, 'Childrens songs');
INSERT INTO categories (id_categories, categories) VALUES (627, 'Cognitive therapy');
INSERT INTO categories (id_categories, categories) VALUES (628, 'UNIX System V (Computer file)');
INSERT INTO categories (id_categories, categories) VALUES (629, 'Cornwall (England : County)');
INSERT INTO categories (id_categories, categories) VALUES (630, 'Color in textile crafts');
INSERT INTO categories (id_categories, categories) VALUES (631, 'Courtesans');
INSERT INTO categories (id_categories, categories) VALUES (632, 'Art, Dutch');
INSERT INTO categories (id_categories, categories) VALUES (633, 'Avarice');
INSERT INTO categories (id_categories, categories) VALUES (634, 'Anthropology');
INSERT INTO categories (id_categories, categories) VALUES (635, 'Astronauts');
INSERT INTO categories (id_categories, categories) VALUES (636, 'Hollywood (Los Angeles, Calif.)');
INSERT INTO categories (id_categories, categories) VALUES (637, 'Electric engineering');
INSERT INTO categories (id_categories, categories) VALUES (638, 'Marlowe, Thomas (Fictitious character)');
INSERT INTO categories (id_categories, categories) VALUES (639, 'Large type books');
INSERT INTO categories (id_categories, categories) VALUES (640, 'Consumer satisfaction');
INSERT INTO categories (id_categories, categories) VALUES (641, 'Microsoft .NET Framework');
INSERT INTO categories (id_categories, categories) VALUES (642, 'American poetry');
INSERT INTO categories (id_categories, categories) VALUES (643, 'French drama');
INSERT INTO categories (id_categories, categories) VALUES (644, 'Czech culture');
INSERT INTO categories (id_categories, categories) VALUES (645, 'Deep ecology');
INSERT INTO categories (id_categories, categories) VALUES (646, 'Organizational behavior');
INSERT INTO categories (id_categories, categories) VALUES (647, 'Honesty');
INSERT INTO categories (id_categories, categories) VALUES (648, '44 Scotland Street (Edinburgh, Scotland : Imaginary place)');
INSERT INTO categories (id_categories, categories) VALUES (649, 'Coloring books');
INSERT INTO categories (id_categories, categories) VALUES (650, 'Readers (Primary)');
INSERT INTO categories (id_categories, categories) VALUES (651, 'Families in art');
INSERT INTO categories (id_categories, categories) VALUES (652, 'Cookery, French');
INSERT INTO categories (id_categories, categories) VALUES (653, 'Conversation analysis');
INSERT INTO categories (id_categories, categories) VALUES (654, 'Lesbians');
INSERT INTO categories (id_categories, categories) VALUES (655, 'Entrepreneurship.');
INSERT INTO categories (id_categories, categories) VALUES (656, 'PHILOSOPHY');
INSERT INTO categories (id_categories, categories) VALUES (657, 'Cricket players');
INSERT INTO categories (id_categories, categories) VALUES (658, 'Ayodhya (Faizabad, India)');
INSERT INTO categories (id_categories, categories) VALUES (659, 'Crime');
INSERT INTO categories (id_categories, categories) VALUES (660, 'COMICS & GRAPHIC NOVELS');
INSERT INTO categories (id_categories, categories) VALUES (661, 'Cambodia');
INSERT INTO categories (id_categories, categories) VALUES (662, 'Gambling systems');
INSERT INTO categories (id_categories, categories) VALUES (663, 'Theologians.');
INSERT INTO categories (id_categories, categories) VALUES (664, 'Nebraska');
INSERT INTO categories (id_categories, categories) VALUES (665, 'Book of Mormon');
INSERT INTO categories (id_categories, categories) VALUES (666, 'Reiki (Healing system)');
INSERT INTO categories (id_categories, categories) VALUES (667, 'Hepatitis');
INSERT INTO categories (id_categories, categories) VALUES (668, 'Customer relations');
INSERT INTO categories (id_categories, categories) VALUES (669, 'Board books');
INSERT INTO categories (id_categories, categories) VALUES (670, 'Chameleons');
INSERT INTO categories (id_categories, categories) VALUES (671, 'Musical revues, comedies, etc');
INSERT INTO categories (id_categories, categories) VALUES (672, 'EDUCATION');
INSERT INTO categories (id_categories, categories) VALUES (673, 'Insomnia');
INSERT INTO categories (id_categories, categories) VALUES (674, 'Best sellers');
INSERT INTO categories (id_categories, categories) VALUES (675, 'Authors, Irish');
INSERT INTO categories (id_categories, categories) VALUES (676, 'Darien (Panama : Province)');
INSERT INTO categories (id_categories, categories) VALUES (677, 'Hatha yoga');
INSERT INTO categories (id_categories, categories) VALUES (678, 'Arthritis');
INSERT INTO categories (id_categories, categories) VALUES (679, 'Communication in politics');
INSERT INTO categories (id_categories, categories) VALUES (680, 'Christian biography');
INSERT INTO categories (id_categories, categories) VALUES (681, 'Depression, Mental');
INSERT INTO categories (id_categories, categories) VALUES (682, 'Monsters');
INSERT INTO categories (id_categories, categories) VALUES (683, 'Friendship');
INSERT INTO categories (id_categories, categories) VALUES (684, 'Impostors and imposture');
INSERT INTO categories (id_categories, categories) VALUES (685, 'African American authors');
INSERT INTO categories (id_categories, categories) VALUES (686, 'Czech language');
INSERT INTO categories (id_categories, categories) VALUES (687, 'Art appreciation');
INSERT INTO categories (id_categories, categories) VALUES (688, 'FreeBSD.');
INSERT INTO categories (id_categories, categories) VALUES (689, 'Blindness');
INSERT INTO categories (id_categories, categories) VALUES (690, 'Grandchildren');
INSERT INTO categories (id_categories, categories) VALUES (691, 'Politics and government');
INSERT INTO categories (id_categories, categories) VALUES (692, 'Humorous stories');
INSERT INTO categories (id_categories, categories) VALUES (693, 'Cognition');
INSERT INTO categories (id_categories, categories) VALUES (694, 'Law examinations');
INSERT INTO categories (id_categories, categories) VALUES (695, 'Caricatures and cartoons');
INSERT INTO categories (id_categories, categories) VALUES (696, 'Shot glasses');
INSERT INTO categories (id_categories, categories) VALUES (697, 'Educational sociology');
INSERT INTO categories (id_categories, categories) VALUES (698, 'Hindu hymns');
INSERT INTO categories (id_categories, categories) VALUES (699, 'Spirit writings');
INSERT INTO categories (id_categories, categories) VALUES (700, 'Fruit');
INSERT INTO categories (id_categories, categories) VALUES (701, 'Alcoholic beverages');
INSERT INTO categories (id_categories, categories) VALUES (702, 'Witches');
INSERT INTO categories (id_categories, categories) VALUES (703, 'Church work with the terminally ill');
INSERT INTO categories (id_categories, categories) VALUES (704, 'Authors spouses');
INSERT INTO categories (id_categories, categories) VALUES (705, 'Experimental fiction');
INSERT INTO categories (id_categories, categories) VALUES (706, 'Back');
INSERT INTO categories (id_categories, categories) VALUES (707, 'Latin America');
INSERT INTO categories (id_categories, categories) VALUES (708, 'Creationism');
INSERT INTO categories (id_categories, categories) VALUES (709, 'Iran');
INSERT INTO categories (id_categories, categories) VALUES (710, 'Discourse analysis');
INSERT INTO categories (id_categories, categories) VALUES (711, 'Soul mates');
INSERT INTO categories (id_categories, categories) VALUES (712, 'Vietnam War, 1961-1975');
INSERT INTO categories (id_categories, categories) VALUES (713, 'Mothers and sons');
INSERT INTO categories (id_categories, categories) VALUES (714, 'Christian ethics');
INSERT INTO categories (id_categories, categories) VALUES (715, 'Second Advent');
INSERT INTO categories (id_categories, categories) VALUES (716, 'Automobiles, Military');
INSERT INTO categories (id_categories, categories) VALUES (717, 'Bacteria');
INSERT INTO categories (id_categories, categories) VALUES (718, 'Electric wiring');
INSERT INTO categories (id_categories, categories) VALUES (719, 'Professional employees');
INSERT INTO categories (id_categories, categories) VALUES (720, 'Chief executive officers');
INSERT INTO categories (id_categories, categories) VALUES (721, 'Autobiography');
INSERT INTO categories (id_categories, categories) VALUES (722, 'Canadians');
INSERT INTO categories (id_categories, categories) VALUES (723, 'Scotland');
INSERT INTO categories (id_categories, categories) VALUES (724, 'Cap dAgde (France)');
INSERT INTO categories (id_categories, categories) VALUES (725, 'College students');
INSERT INTO categories (id_categories, categories) VALUES (726, 'Islam');
INSERT INTO categories (id_categories, categories) VALUES (727, 'Language and languages');
INSERT INTO categories (id_categories, categories) VALUES (728, 'COMPUTERS');
INSERT INTO categories (id_categories, categories) VALUES (729, 'Turning (Lathe work)');
INSERT INTO categories (id_categories, categories) VALUES (730, 'Entertainers');
INSERT INTO categories (id_categories, categories) VALUES (731, 'Angels');
INSERT INTO categories (id_categories, categories) VALUES (732, 'Private investigators');
INSERT INTO categories (id_categories, categories) VALUES (733, 'Hispanic Americans');
INSERT INTO categories (id_categories, categories) VALUES (734, 'COMICS & GRAPHIC NOVELS.');
INSERT INTO categories (id_categories, categories) VALUES (735, 'Ardennes, Battle of the, 1944-1945');
INSERT INTO categories (id_categories, categories) VALUES (736, 'Ritterkreuz.');
INSERT INTO categories (id_categories, categories) VALUES (737, 'Alchemy');
INSERT INTO categories (id_categories, categories) VALUES (738, 'Fremdsprachenunterricht');
INSERT INTO categories (id_categories, categories) VALUES (739, 'End of the world.');
INSERT INTO categories (id_categories, categories) VALUES (740, 'Memory');
INSERT INTO categories (id_categories, categories) VALUES (741, 'Sonatas (Piano)');
INSERT INTO categories (id_categories, categories) VALUES (742, 'Athens (Greece)');
INSERT INTO categories (id_categories, categories) VALUES (743, 'Swimming');
INSERT INTO categories (id_categories, categories) VALUES (744, 'Beowulf');
INSERT INTO categories (id_categories, categories) VALUES (745, 'Insects');
INSERT INTO categories (id_categories, categories) VALUES (746, 'Asthma');
INSERT INTO categories (id_categories, categories) VALUES (747, 'Governesses in literature');
INSERT INTO categories (id_categories, categories) VALUES (748, 'Christianity');
INSERT INTO categories (id_categories, categories) VALUES (749, 'Civilization, Islamic');
INSERT INTO categories (id_categories, categories) VALUES (750, 'Fantasy');
INSERT INTO categories (id_categories, categories) VALUES (751, 'Extraterrestrial beings');
INSERT INTO categories (id_categories, categories) VALUES (752, 'Storytelling performances');
INSERT INTO categories (id_categories, categories) VALUES (753, 'Tibetan literature');
INSERT INTO categories (id_categories, categories) VALUES (754, 'College department heads');
INSERT INTO categories (id_categories, categories) VALUES (755, 'Business networks');
INSERT INTO categories (id_categories, categories) VALUES (756, 'Edible mushrooms');
INSERT INTO categories (id_categories, categories) VALUES (757, 'Gambling');
INSERT INTO categories (id_categories, categories) VALUES (758, 'Animated films');
INSERT INTO categories (id_categories, categories) VALUES (759, 'Barcelona (Spain)');
INSERT INTO categories (id_categories, categories) VALUES (760, 'Holocaust, Jewish (1939-1945)');
INSERT INTO categories (id_categories, categories) VALUES (761, 'Reformation.');
INSERT INTO categories (id_categories, categories) VALUES (762, 'Indians in art');
INSERT INTO categories (id_categories, categories) VALUES (763, 'Acting');
INSERT INTO categories (id_categories, categories) VALUES (764, 'Dating (Social customs)');
INSERT INTO categories (id_categories, categories) VALUES (765, 'Breast');
INSERT INTO categories (id_categories, categories) VALUES (766, 'Phenomenology');
INSERT INTO categories (id_categories, categories) VALUES (767, 'Decorative arts');
INSERT INTO categories (id_categories, categories) VALUES (768, 'Industrial safety');
INSERT INTO categories (id_categories, categories) VALUES (769, 'Ceramic tableware');
INSERT INTO categories (id_categories, categories) VALUES (770, 'Caribbean Area');
INSERT INTO categories (id_categories, categories) VALUES (771, 'Cabinet officers');
INSERT INTO categories (id_categories, categories) VALUES (772, 'Marketing');
INSERT INTO categories (id_categories, categories) VALUES (773, 'Polish language');
INSERT INTO categories (id_categories, categories) VALUES (774, 'Knit goods');
INSERT INTO categories (id_categories, categories) VALUES (775, 'Canadian Rockies (B.C. and Alta.)');
INSERT INTO categories (id_categories, categories) VALUES (776, 'Employee motivation');
INSERT INTO categories (id_categories, categories) VALUES (777, 'Clowns');
INSERT INTO categories (id_categories, categories) VALUES (778, 'Fathers Day - Children Fiction');
INSERT INTO categories (id_categories, categories) VALUES (779, 'Belden, Trixie (Fictitious character)');
INSERT INTO categories (id_categories, categories) VALUES (780, 'Deer hunting');
INSERT INTO categories (id_categories, categories) VALUES (781, 'Africa, North');
INSERT INTO categories (id_categories, categories) VALUES (782, 'Revolutions');
INSERT INTO categories (id_categories, categories) VALUES (783, 'Arizona');
INSERT INTO categories (id_categories, categories) VALUES (784, 'Cambridgeshire (England)');
INSERT INTO categories (id_categories, categories) VALUES (785, 'Commercial real estate');
INSERT INTO categories (id_categories, categories) VALUES (786, 'Authors, Spanish');
INSERT INTO categories (id_categories, categories) VALUES (787, 'Childbirth');
INSERT INTO categories (id_categories, categories) VALUES (788, 'Air forces');
INSERT INTO categories (id_categories, categories) VALUES (789, 'HISTORY');
INSERT INTO categories (id_categories, categories) VALUES (790, 'Work');
INSERT INTO categories (id_categories, categories) VALUES (791, 'Internet dating');
INSERT INTO categories (id_categories, categories) VALUES (792, 'Cuban American families');
INSERT INTO categories (id_categories, categories) VALUES (793, 'Dieu - Amour');
INSERT INTO categories (id_categories, categories) VALUES (794, 'Dolls');
INSERT INTO categories (id_categories, categories) VALUES (795, 'Theology');
INSERT INTO categories (id_categories, categories) VALUES (796, 'Motherhood');
INSERT INTO categories (id_categories, categories) VALUES (797, 'Bratislava (Slovakia)');
INSERT INTO categories (id_categories, categories) VALUES (798, 'Earth (Planet)');
INSERT INTO categories (id_categories, categories) VALUES (799, 'Fantasy fiction');
INSERT INTO categories (id_categories, categories) VALUES (800, 'JUVENILE FICTION');
INSERT INTO categories (id_categories, categories) VALUES (801, 'Carnival');
INSERT INTO categories (id_categories, categories) VALUES (802, 'Saturn launch vehicles.');
INSERT INTO categories (id_categories, categories) VALUES (803, 'Computer architecture');
INSERT INTO categories (id_categories, categories) VALUES (804, 'African American lesbians');
INSERT INTO categories (id_categories, categories) VALUES (805, 'Spanish literature');
INSERT INTO categories (id_categories, categories) VALUES (806, 'Architecture, Roman');
INSERT INTO categories (id_categories, categories) VALUES (807, 'Lunar surface vehicles');
INSERT INTO categories (id_categories, categories) VALUES (808, 'Abandoned children');
INSERT INTO categories (id_categories, categories) VALUES (809, 'Domestic animals');
INSERT INTO categories (id_categories, categories) VALUES (810, 'Calculus');
INSERT INTO categories (id_categories, categories) VALUES (811, 'Childrens literature, English');
INSERT INTO categories (id_categories, categories) VALUES (812, 'Wizards');
INSERT INTO categories (id_categories, categories) VALUES (813, 'Computer-aided design');
INSERT INTO categories (id_categories, categories) VALUES (814, 'Homeless persons');
INSERT INTO categories (id_categories, categories) VALUES (815, 'Indian women');
INSERT INTO categories (id_categories, categories) VALUES (816, 'Business travel.');
INSERT INTO categories (id_categories, categories) VALUES (817, 'Atomic structure');
INSERT INTO categories (id_categories, categories) VALUES (818, 'Boats and boating');
INSERT INTO categories (id_categories, categories) VALUES (819, 'Self (Philosophy).');
INSERT INTO categories (id_categories, categories) VALUES (820, 'Bulimia');
INSERT INTO categories (id_categories, categories) VALUES (821, 'Bar mitzvah');
INSERT INTO categories (id_categories, categories) VALUES (822, 'Conspiracies');
INSERT INTO categories (id_categories, categories) VALUES (823, 'Authorship');
INSERT INTO categories (id_categories, categories) VALUES (824, 'BUSINESS & ECONOMICS');
INSERT INTO categories (id_categories, categories) VALUES (825, 'Distributed operating systems (Computers)');
INSERT INTO categories (id_categories, categories) VALUES (826, 'Gold mines and mining');
INSERT INTO categories (id_categories, categories) VALUES (827, 'Poland');
INSERT INTO categories (id_categories, categories) VALUES (828, 'Prophecies (Occultism)');
INSERT INTO categories (id_categories, categories) VALUES (829, 'Bass guitar');
INSERT INTO categories (id_categories, categories) VALUES (830, 'Balsan, Consuelo Vanderbilt');
INSERT INTO categories (id_categories, categories) VALUES (831, 'Ethiopia');
INSERT INTO categories (id_categories, categories) VALUES (832, 'Theosophy');
INSERT INTO categories (id_categories, categories) VALUES (833, 'New York (N.Y.)');
INSERT INTO categories (id_categories, categories) VALUES (834, 'Genetic disorders');
INSERT INTO categories (id_categories, categories) VALUES (835, 'Farm life');
INSERT INTO categories (id_categories, categories) VALUES (836, 'Cooperative societies');
INSERT INTO categories (id_categories, categories) VALUES (837, 'Public speaking');
INSERT INTO categories (id_categories, categories) VALUES (838, 'Art, Modern');
INSERT INTO categories (id_categories, categories) VALUES (839, 'African American women');
INSERT INTO categories (id_categories, categories) VALUES (840, 'East Asia');
INSERT INTO categories (id_categories, categories) VALUES (841, 'Sinclair, Paul (Fictitious character)');
INSERT INTO categories (id_categories, categories) VALUES (842, 'Categories (Philosophy)');
INSERT INTO categories (id_categories, categories) VALUES (843, 'Big Sur Region (Calif.)');
INSERT INTO categories (id_categories, categories) VALUES (844, 'Cardiology');
INSERT INTO categories (id_categories, categories) VALUES (845, 'Self-actualization (Psychology)');
INSERT INTO categories (id_categories, categories) VALUES (846, 'Niagara Falls (N.Y. and Ont.)');
INSERT INTO categories (id_categories, categories) VALUES (847, 'Mammals');
INSERT INTO categories (id_categories, categories) VALUES (848, 'Fast food restaurants');
INSERT INTO categories (id_categories, categories) VALUES (849, 'Christianity and other religions');
INSERT INTO categories (id_categories, categories) VALUES (850, 'Computer software');
INSERT INTO categories (id_categories, categories) VALUES (851, 'Boys');
INSERT INTO categories (id_categories, categories) VALUES (852, 'Corporations');
INSERT INTO categories (id_categories, categories) VALUES (853, 'Horses');
INSERT INTO categories (id_categories, categories) VALUES (854, 'Lewis and Clark Expedition');
INSERT INTO categories (id_categories, categories) VALUES (855, 'Sailboats');
INSERT INTO categories (id_categories, categories) VALUES (856, 'Advaita');
INSERT INTO categories (id_categories, categories) VALUES (857, 'African American painters');
INSERT INTO categories (id_categories, categories) VALUES (858, 'Director (Computer file)');
INSERT INTO categories (id_categories, categories) VALUES (859, 'Volkswagen Polo automobile');
INSERT INTO categories (id_categories, categories) VALUES (860, 'Art deco (Architecture)');
INSERT INTO categories (id_categories, categories) VALUES (861, 'Russian language');
INSERT INTO categories (id_categories, categories) VALUES (862, 'C (Computer program language)');
INSERT INTO categories (id_categories, categories) VALUES (863, 'Anatomy');
INSERT INTO categories (id_categories, categories) VALUES (864, 'Administrative agencies');
INSERT INTO categories (id_categories, categories) VALUES (865, 'Australian wit and humor, Pictorial');
INSERT INTO categories (id_categories, categories) VALUES (866, 'Orkney (Scotland)');
INSERT INTO categories (id_categories, categories) VALUES (867, 'Proverbs');
INSERT INTO categories (id_categories, categories) VALUES (868, 'Russia (Federation)');
INSERT INTO categories (id_categories, categories) VALUES (869, 'Meat');
INSERT INTO categories (id_categories, categories) VALUES (870, 'Community organization');
INSERT INTO categories (id_categories, categories) VALUES (871, 'Anabaptists');
INSERT INTO categories (id_categories, categories) VALUES (872, 'Child Welfare');
INSERT INTO categories (id_categories, categories) VALUES (873, 'Automobiles');
INSERT INTO categories (id_categories, categories) VALUES (874, 'African Language');
INSERT INTO categories (id_categories, categories) VALUES (875, 'Motion picture producers and directors');
INSERT INTO categories (id_categories, categories) VALUES (876, 'Horror films');
INSERT INTO categories (id_categories, categories) VALUES (877, 'Silver jewelry');
INSERT INTO categories (id_categories, categories) VALUES (878, 'Environmental protection');
INSERT INTO categories (id_categories, categories) VALUES (879, 'Loss (Psychology)');
INSERT INTO categories (id_categories, categories) VALUES (880, 'Health promotion');
INSERT INTO categories (id_categories, categories) VALUES (881, 'Ciphers');
INSERT INTO categories (id_categories, categories) VALUES (882, 'Feminist economics');
INSERT INTO categories (id_categories, categories) VALUES (883, 'Silhouettes');
INSERT INTO categories (id_categories, categories) VALUES (884, 'Amsterdam (Netherlands)');
INSERT INTO categories (id_categories, categories) VALUES (885, 'Vienna (Austria)');
INSERT INTO categories (id_categories, categories) VALUES (886, 'Citation of legal authorities');
INSERT INTO categories (id_categories, categories) VALUES (887, 'North Carolina');
INSERT INTO categories (id_categories, categories) VALUES (888, 'Civil disobedience');
INSERT INTO categories (id_categories, categories) VALUES (889, 'New England');
INSERT INTO categories (id_categories, categories) VALUES (890, 'World Series (Baseball)');
INSERT INTO categories (id_categories, categories) VALUES (891, 'Fairies');
INSERT INTO categories (id_categories, categories) VALUES (892, 'Artillery, Field and mountain');
INSERT INTO categories (id_categories, categories) VALUES (893, 'Incas');
INSERT INTO categories (id_categories, categories) VALUES (894, 'Behavior disorders in children');
INSERT INTO categories (id_categories, categories) VALUES (895, 'Success');
INSERT INTO categories (id_categories, categories) VALUES (896, 'Guineafowl');
INSERT INTO categories (id_categories, categories) VALUES (897, 'Plantation life');
INSERT INTO categories (id_categories, categories) VALUES (898, 'Audiobooks');
INSERT INTO categories (id_categories, categories) VALUES (899, 'Cooking (Wine)');
INSERT INTO categories (id_categories, categories) VALUES (900, 'Mortars (Ordnance)');
INSERT INTO categories (id_categories, categories) VALUES (901, 'Food');
INSERT INTO categories (id_categories, categories) VALUES (902, 'Legal research');
INSERT INTO categories (id_categories, categories) VALUES (903, 'Ocean travel');
INSERT INTO categories (id_categories, categories) VALUES (904, 'Digital media');
INSERT INTO categories (id_categories, categories) VALUES (905, 'Keyboarding');
INSERT INTO categories (id_categories, categories) VALUES (906, 'Desserts');
INSERT INTO categories (id_categories, categories) VALUES (907, 'Czech Americans');
INSERT INTO categories (id_categories, categories) VALUES (908, 'Counterculture');
INSERT INTO categories (id_categories, categories) VALUES (909, 'Newspapers');
INSERT INTO categories (id_categories, categories) VALUES (910, 'Common bean');
INSERT INTO categories (id_categories, categories) VALUES (911, 'Food supply');
INSERT INTO categories (id_categories, categories) VALUES (912, 'Kings Canyon National Park (Calif.)');
INSERT INTO categories (id_categories, categories) VALUES (913, 'Computer graphics');
INSERT INTO categories (id_categories, categories) VALUES (914, 'Composers');
INSERT INTO categories (id_categories, categories) VALUES (915, 'Greek poetry');
INSERT INTO categories (id_categories, categories) VALUES (916, 'Activity programs in education');
INSERT INTO categories (id_categories, categories) VALUES (917, 'Cake decorating');
INSERT INTO categories (id_categories, categories) VALUES (918, 'People with disabilities');
INSERT INTO categories (id_categories, categories) VALUES (919, 'Deverry (Imaginary place)');
INSERT INTO categories (id_categories, categories) VALUES (920, 'Koi');
INSERT INTO categories (id_categories, categories) VALUES (921, 'American Sign Language');
INSERT INTO categories (id_categories, categories) VALUES (922, 'Emigration and immigration');
INSERT INTO categories (id_categories, categories) VALUES (923, 'Fire fighters');
INSERT INTO categories (id_categories, categories) VALUES (924, 'Home economics');
INSERT INTO categories (id_categories, categories) VALUES (925, 'Charms');
INSERT INTO categories (id_categories, categories) VALUES (926, 'BIBLES');
INSERT INTO categories (id_categories, categories) VALUES (927, 'Behavior modification');
INSERT INTO categories (id_categories, categories) VALUES (928, 'Sunflowers');
INSERT INTO categories (id_categories, categories) VALUES (929, 'Popular culture');
INSERT INTO categories (id_categories, categories) VALUES (930, 'Anger');
INSERT INTO categories (id_categories, categories) VALUES (931, 'Murder');
INSERT INTO categories (id_categories, categories) VALUES (932, 'Solar collectors');
INSERT INTO categories (id_categories, categories) VALUES (933, 'Algeria');
INSERT INTO categories (id_categories, categories) VALUES (934, 'Tarot');
INSERT INTO categories (id_categories, categories) VALUES (935, 'Desolation Wilderness (Calif.)');
INSERT INTO categories (id_categories, categories) VALUES (936, 'Werewolves');
INSERT INTO categories (id_categories, categories) VALUES (937, 'Painting');
INSERT INTO categories (id_categories, categories) VALUES (938, 'Agriculture');
INSERT INTO categories (id_categories, categories) VALUES (939, 'Hopi Indians');
INSERT INTO categories (id_categories, categories) VALUES (940, 'Anglican Communion');
INSERT INTO categories (id_categories, categories) VALUES (941, 'SAT (Educational test)');
INSERT INTO categories (id_categories, categories) VALUES (942, 'Colombo (Sri Lanka)');
